name: Cargo checkmate

defaults:
  run:
    working-directory: secrets

on:
  schedule:
    - cron: '44 4 * * *' # Run 04:44 UTC
    
  workflow_dispatch:

permissions:
  contents: read
  
jobs:
  check_date:
    runs-on: ubuntu-latest
    name: Check latest commit
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
      - name: print latest_commit
        run: echo ${{ github.sha }}

      - id: should_run
        continue-on-error: true
        name: check latest commit is less than a day
        if: ${{ github.event_name == 'schedule' }}
        run: test -z $(git rev-list  --after="24 hours"  ${{ github.sha }}) && echo "::set-output name=should_run::false"
        
  analyze:
    needs: check_date
    if: ${{ needs.check_date.outputs.should_run != 'false' }}
    
    runs-on: ubuntu-latest

    env:
      CARGO_TERM_COLOR: always
      
    steps:
    - uses: actions/checkout@v3
    - name: Install checkmate
      run: cargo install cargo-checkmate
    - name: Run checkmate
      run: cargo checkmate
