name: Cargo checkmate

defaults:
  run:
    working-directory: secrets

on:
  schedule:
    - cron: "16 10 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install checkmate
      run: cargo install cargo-checkmate
    - name: Run checkmate
      run: cargo checkmate
